@startuml
|Пользователь|
start
:Открывает мобильное приложение;
:Авторизуется (OAuth 2.0);
:Разрешает доступ к геолокации;

|Система|
:Получает координаты устройства;
:Определяет текущее местоположение;
:Отображает карту с текущим местоположением;
:Загружает список геозон пользователя (geofence_service);
:Отображает геозоны на карте;

repeat
    :Пользователь перемещается;
    |Система|
    :Получает новые координаты;
    :Обновляет местоположение на карте;
    :Сохраняет историю перемещений (TimescaleDB);
    :Проверяет пересечение с геозонами (geofence_service);
    if (Пересечение с геозоной?) then (да)
        :Определяет тип события (вход/выход);
        :Отправляет уведомление (notification_service);
    endif
    if (Пользователь взаимодействует с картой?) then (да)
        if (Добавление геозоны?) then (да)
            :Рисует геозону на карте;
            :Сохраняет геозону (geofence_service);
        elseif (Удаление геозоны?) then (да)
            :Удаляет геозону с карты;
            :Удаляет геозону (geofence_service);
        elseif (Просмотр истории перемещений?) then (да)
            :Загружает историю перемещений (TimescaleDB);
            :Отображает историю на карте;
        endif
    endif
    if (Пользователь нажал "Выход"?) then (да)
        break
    endif
repeat while (Приложение открыто?) is (да)

:Приложение закрыто;
|Система|
:Прекращает отслеживание местоположения;
stop
@enduml